// ─────────────────────────────────────────────────────────────
// SEED DATA — initial products loaded into RAM on server start
// ─────────────────────────────────────────────────────────────

const SEED = [
  { name:'Poplin Regular',     category:'Tops',        price:75,  stock:5,  colors:['Pink','Blue','White'],              sizes:['XS','S','M','L','XL'],      description:'Pure peached cotton poplin shirt.', features:['Pure peached cotton poplin','Tommy Hilfiger flag embroidery','Flex technology','All-over vertical stripe','Button-down collar','Rounded one-button cuffs'], image:'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80', createdAt:'2024-01-01T00:00:00Z' },
  { name:'TH Flex Slim-fit',   category:'Tops',        price:60,  stock:6,  colors:['Pink','Light Blue','White','Navy'], sizes:['XS','S','M','L','XL'],      description:'Slim-fit shirt with flex technology.', features:['Flex technology','Slim fit silhouette','Button-down collar','Tommy Hilfiger branding','Stretch cotton blend'], image:'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80', createdAt:'2024-01-02T00:00:00Z' },
  { name:'Oxford Regular',     category:'Tops',        price:100, stock:7,  colors:['Black','Navy'],                    sizes:['S','M','L','XL','XXL'],     description:'Classic Oxford shirt in premium cotton.', features:['100% premium cotton Oxford weave','Regular fit','Button-down collar','Classic chest pocket','Single button cuffs'], image:'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=400&q=80', createdAt:'2024-01-03T00:00:00Z' },
  { name:'Linen Summer Shirt', category:'Tops',        price:85,  stock:12, colors:['Beige','White','Sage'],             sizes:['XS','S','M','L','XL'],      description:'Breathable linen shirt for warm weather.', features:['100% pure linen','Relaxed fit','Roll-up sleeve tabs','Chest patch pocket','Mother of pearl buttons'], image:'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&q=80', createdAt:'2024-01-04T00:00:00Z' },
  { name:'Merino Polo',        category:'Tops',        price:120, stock:9,  colors:['Burgundy','Navy','Forest Green'],  sizes:['S','M','L','XL'],           description:'Luxurious Merino wool polo.', features:['100% Merino wool','Classic polo collar','Three-button placket','Ribbed cuffs and hem','Anti-pilling treatment'], image:'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80', createdAt:'2024-01-05T00:00:00Z' },
  { name:'Cashmere Turtleneck',category:'Tops',        price:195, stock:4,  colors:['Camel','Charcoal','Ivory'],        sizes:['XS','S','M','L'],           description:'Refined cashmere turtleneck.', features:['Grade A Mongolian cashmere','Fine knit construction','Ribbed turtleneck collar','Slim cut body','Dry clean only'], image:'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&q=80', createdAt:'2024-01-06T00:00:00Z' },
  { name:'Tailored Blazer',    category:'Outerwear',   price:340, stock:3,  colors:['Navy','Charcoal','Cream'],         sizes:['S','M','L','XL'],           description:'Impeccably tailored blazer in Italian wool.', features:['Italian wool blend','Slim lapel','Two-button single-breasted','Functional sleeve buttons','Half canvas construction'], image:'https://images.unsplash.com/photo-1594938298603-c8148c4b4da7?w=400&q=80', createdAt:'2024-01-07T00:00:00Z' },
  { name:'Slim Chino Trousers',category:'Bottoms',     price:95,  stock:15, colors:['Khaki','Navy','Olive','Stone'],    sizes:['XS','S','M','L','XL','XXL'],description:'Versatile slim-fit chinos.', features:['98% cotton 2% elastane','Slim fit throughout','Five-pocket design','Zip fly with button','Machine washable'], image:'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80', createdAt:'2024-01-08T00:00:00Z' },
  { name:'Wrap Midi Dress',    category:'Dresses',     price:180, stock:8,  colors:['Forest Green','Rust','Midnight'], sizes:['XS','S','M','L'],           description:'Fluid wrap dress in silk-touch fabric.', features:['Viscose-silk blend','Adjustable wrap tie','Midi length','V-neckline','Hand wash cold'], image:'https://images.unsplash.com/photo-1623609163859-ca93c959b98a?w=400&q=80', createdAt:'2024-01-09T00:00:00Z' },
  { name:'Leather Belt',       category:'Accessories', price:65,  stock:20, colors:['Black','Cognac','Brown'],          sizes:['S','M','L','XL'],           description:'Full-grain leather belt with brushed gold buckle.', features:['Full-grain calfskin leather','Brushed gold hardware','Adjustable fit','Width: 3.5 cm','Made in Italy'], image:'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&q=80', createdAt:'2024-01-10T00:00:00Z' },
  { name:'Cashmere Wrap Coat', category:'Outerwear',   price:520, stock:2,  colors:['Camel','Burgundy'],               sizes:['XS','S','M','L'],           description:'Statement wrap coat in pure cashmere.', features:['100% pure cashmere','Self-tie belt','Notch lapel','Two front pockets','Dry clean only'], image:'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=400&q=80', createdAt:'2024-01-11T00:00:00Z' },
  { name:'Gold Chain Necklace',category:'Accessories', price:89,  stock:25, colors:['Gold','Rose Gold'],               sizes:['One Size'],                 description:'Delicate layering necklace in 18k gold-plated brass.', features:['18k gold plating','Lobster claw clasp','Length: 45cm','Hypoallergenic','Comes in gift box'], image:'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&q=80', createdAt:'2024-01-12T00:00:00Z' },
];

export default SEED;
